apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qev11d5qt-dotnet-basic
  janus-idp.io/tekton: qev11d5qt-dotnet-basic
  backstage.io/kubernetes-id: qev11d5qt-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qev11d5qt-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
